# Generated by Django 5.0.6 on 2024-06-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
    ]
