# Generated by Django 5.0.6 on 2024-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0003_alter_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture'), ('photography', 'Photography')], max_length=100),
        ),
    ]
